### ISSUE TITLE
Not working for elements added after ajax call

### ISSUE THREAD

**Issue by nehagaur8** [PhilippeMarcMeyer/bootstrapSelect#1]
1. I added a drop down using ajax on the page.

2. After ajax call done function I have added an element (div containing drop down ) on the page.

3. Then I used init function 
optionSelection1.bootstrapSelect("init"); 
to apply ul li to the dropdown. But it didn't work.

**Comment by PhilippeMarcMeyer** [comment]
Hello Nehagaur,
I will need a bit more informations.
What versions of bootstrap and jQuery do you use ?
Could you provide a few lines of code ?

Thnak you for your help

Philip
